//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 

namespace APP
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "UpLoadDownLoadRecordServiceSoapBinding", Namespace = "http://record.psr.com/")]
    public partial class UpLoadDownLoadRecordService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback UpLoadRecordOperationCompleted;

        private System.Threading.SendOrPostCallback DownLoadRecordOperationCompleted;

        /// <remarks/>
        public UpLoadDownLoadRecordService()
        {
            this.Url = "http://localhost:8080/PSRWS/services/UpLoadDownLoadRecordPort";
        }

        /// <remarks/>
        public event UpLoadRecordCompletedEventHandler UpLoadRecordCompleted;

        /// <remarks/>
        public event DownLoadRecordCompletedEventHandler DownLoadRecordCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:UpLoadRecord", RequestNamespace = "http://record.psr.com/", ResponseNamespace = "http://record.psr.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpLoadRecord([System.Xml.Serialization.XmlElementAttribute("arg0", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] record[] arg0)
        {
            this.Invoke("UpLoadRecord", new object[] {
                    arg0});
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpLoadRecord(record[] arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpLoadRecord", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public void EndUpLoadRecord(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void UpLoadRecordAsync(record[] arg0)
        {
            this.UpLoadRecordAsync(arg0, null);
        }

        /// <remarks/>
        public void UpLoadRecordAsync(record[] arg0, object userState)
        {
            if ((this.UpLoadRecordOperationCompleted == null))
            {
                this.UpLoadRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpLoadRecordOperationCompleted);
            }
            this.InvokeAsync("UpLoadRecord", new object[] {
                    arg0}, this.UpLoadRecordOperationCompleted, userState);
        }

        private void OnUpLoadRecordOperationCompleted(object arg)
        {
            if ((this.UpLoadRecordCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpLoadRecordCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:DownLoadRecord", RequestNamespace = "http://record.psr.com/", ResponseNamespace = "http://record.psr.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public record[] DownLoadRecord([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1)
        {
            object[] results = this.Invoke("DownLoadRecord", new object[] {
                    arg0,
                    arg1});
            return ((record[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDownLoadRecord(string arg0, string arg1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DownLoadRecord", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
        }

        /// <remarks/>
        public record[] EndDownLoadRecord(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((record[])(results[0]));
        }

        /// <remarks/>
        public void DownLoadRecordAsync(string arg0, string arg1)
        {
            this.DownLoadRecordAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void DownLoadRecordAsync(string arg0, string arg1, object userState)
        {
            if ((this.DownLoadRecordOperationCompleted == null))
            {
                this.DownLoadRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownLoadRecordOperationCompleted);
            }
            this.InvokeAsync("DownLoadRecord", new object[] {
                    arg0,
                    arg1}, this.DownLoadRecordOperationCompleted, userState);
        }

        private void OnDownLoadRecordOperationCompleted(object arg)
        {
            if ((this.DownLoadRecordCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownLoadRecordCompleted(this, new DownLoadRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://record.psr.com/")]
    public partial class record
    {

        private string _idField;

        private string _facilityField;

        private string _countField;

        private string _yaosubianhaoField;

        private string _zhuangtibianhaoField;

        private string _danweiField;

        private string _inputUserField;

        private string _inputUserSuoXieField;

        private string _statusField;

        private bool _haveAttachedField;

        private bool _HaveruoxiangField;

        private bool _HaveqiangxiangField;

        private System.DateTime _inputTimeField;

        private bool _inputTimeFieldSpecified;

        private bool _isDeleteField;

        private string _topicField;

        private string _resultField;

        private string _recordDesciptionField;

        private fact[] _factsField;

        private string _approveByField;

        private string _commentsField;

        private System.DateTime _approveTimeField;

        private bool _approveTimeFieldSpecified;

        private bool _isUpLoadField;

        private bool _isUpDatedField;

        private System.DateTime _UpLoadedTimeField;

        private bool _UpLoadedTimeFieldSpecified;

        private System.DateTime _UpdatedTimeField;

        private bool _UpdatedTimeFieldSpecified;

        private string _sendBackReasonField;

        private recordResult[] _resultsField;

        private bool _isActivityInspectionField;

        private bool _isWalkDownField;

        private bool _isDocumentRevisionField;

        private bool _isCommunicationField;

        private bool _isComplianceField;

        private string _equiptmentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _id
        {
            get
            {
                return this._idField;
            }
            set
            {
                this._idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _facility
        {
            get
            {
                return this._facilityField;
            }
            set
            {
                this._facilityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _count
        {
            get
            {
                return this._countField;
            }
            set
            {
                this._countField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _yaosubianhao
        {
            get
            {
                return this._yaosubianhaoField;
            }
            set
            {
                this._yaosubianhaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _zhuangtibianhao
        {
            get
            {
                return this._zhuangtibianhaoField;
            }
            set
            {
                this._zhuangtibianhaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _danwei
        {
            get
            {
                return this._danweiField;
            }
            set
            {
                this._danweiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _inputUser
        {
            get
            {
                return this._inputUserField;
            }
            set
            {
                this._inputUserField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _inputUserSuoXie
        {
            get
            {
                return this._inputUserSuoXieField;
            }
            set
            {
                this._inputUserSuoXieField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _status
        {
            get
            {
                return this._statusField;
            }
            set
            {
                this._statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _haveAttached
        {
            get
            {
                return this._haveAttachedField;
            }
            set
            {
                this._haveAttachedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _Haveruoxiang
        {
            get
            {
                return this._HaveruoxiangField;
            }
            set
            {
                this._HaveruoxiangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _Haveqiangxiang
        {
            get
            {
                return this._HaveqiangxiangField;
            }
            set
            {
                this._HaveqiangxiangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime _inputTime
        {
            get
            {
                return this._inputTimeField;
            }
            set
            {
                this._inputTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _inputTimeSpecified
        {
            get
            {
                return this._inputTimeFieldSpecified;
            }
            set
            {
                this._inputTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isDelete
        {
            get
            {
                return this._isDeleteField;
            }
            set
            {
                this._isDeleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _topic
        {
            get
            {
                return this._topicField;
            }
            set
            {
                this._topicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _result
        {
            get
            {
                return this._resultField;
            }
            set
            {
                this._resultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _recordDesciption
        {
            get
            {
                return this._recordDesciptionField;
            }
            set
            {
                this._recordDesciptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_facts", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public fact[] _facts
        {
            get
            {
                return this._factsField;
            }
            set
            {
                this._factsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _approveBy
        {
            get
            {
                return this._approveByField;
            }
            set
            {
                this._approveByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _comments
        {
            get
            {
                return this._commentsField;
            }
            set
            {
                this._commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime _approveTime
        {
            get
            {
                return this._approveTimeField;
            }
            set
            {
                this._approveTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _approveTimeSpecified
        {
            get
            {
                return this._approveTimeFieldSpecified;
            }
            set
            {
                this._approveTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isUpLoad
        {
            get
            {
                return this._isUpLoadField;
            }
            set
            {
                this._isUpLoadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isUpDated
        {
            get
            {
                return this._isUpDatedField;
            }
            set
            {
                this._isUpDatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime _UpLoadedTime
        {
            get
            {
                return this._UpLoadedTimeField;
            }
            set
            {
                this._UpLoadedTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _UpLoadedTimeSpecified
        {
            get
            {
                return this._UpLoadedTimeFieldSpecified;
            }
            set
            {
                this._UpLoadedTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime _UpdatedTime
        {
            get
            {
                return this._UpdatedTimeField;
            }
            set
            {
                this._UpdatedTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _UpdatedTimeSpecified
        {
            get
            {
                return this._UpdatedTimeFieldSpecified;
            }
            set
            {
                this._UpdatedTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _sendBackReason
        {
            get
            {
                return this._sendBackReasonField;
            }
            set
            {
                this._sendBackReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_results", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public recordResult[] _results
        {
            get
            {
                return this._resultsField;
            }
            set
            {
                this._resultsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isActivityInspection
        {
            get
            {
                return this._isActivityInspectionField;
            }
            set
            {
                this._isActivityInspectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isWalkDown
        {
            get
            {
                return this._isWalkDownField;
            }
            set
            {
                this._isWalkDownField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isDocumentRevision
        {
            get
            {
                return this._isDocumentRevisionField;
            }
            set
            {
                this._isDocumentRevisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isCommunication
        {
            get
            {
                return this._isCommunicationField;
            }
            set
            {
                this._isCommunicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isCompliance
        {
            get
            {
                return this._isComplianceField;
            }
            set
            {
                this._isComplianceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _equiptment
        {
            get
            {
                return this._equiptmentField;
            }
            set
            {
                this._equiptmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://record.psr.com/")]
    public partial class fact
    {

        private string _idField;

        private string _recordNoField;

        private string _contentField;

        private string _FuHeXiangField;

        private string _PianChaXiangField;

        private System.DateTime _timeStampField;

        private bool _timeStampFieldSpecified;

        private string strFactStatusField;

        private string strFactApproveCommentField;

        private int _associateResultField;

        private bool _isFhField;

        private bool _isPcField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _id
        {
            get
            {
                return this._idField;
            }
            set
            {
                this._idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _recordNo
        {
            get
            {
                return this._recordNoField;
            }
            set
            {
                this._recordNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _content
        {
            get
            {
                return this._contentField;
            }
            set
            {
                this._contentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _FuHeXiang
        {
            get
            {
                return this._FuHeXiangField;
            }
            set
            {
                this._FuHeXiangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PianChaXiang
        {
            get
            {
                return this._PianChaXiangField;
            }
            set
            {
                this._PianChaXiangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime _timeStamp
        {
            get
            {
                return this._timeStampField;
            }
            set
            {
                this._timeStampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _timeStampSpecified
        {
            get
            {
                return this._timeStampFieldSpecified;
            }
            set
            {
                this._timeStampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strFactStatus
        {
            get
            {
                return this.strFactStatusField;
            }
            set
            {
                this.strFactStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strFactApproveComment
        {
            get
            {
                return this.strFactApproveCommentField;
            }
            set
            {
                this.strFactApproveCommentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int _associateResult
        {
            get
            {
                return this._associateResultField;
            }
            set
            {
                this._associateResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isFh
        {
            get
            {
                return this._isFhField;
            }
            set
            {
                this._isFhField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isPc
        {
            get
            {
                return this._isPcField;
            }
            set
            {
                this._isPcField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://record.psr.com/")]
    public partial class recordResult
    {

        private string _idField;

        private string _recordNoField;

        private string _contentField;

        private string _againstFactsField;

        private bool _isPCField;

        private bool _isFHField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _id
        {
            get
            {
                return this._idField;
            }
            set
            {
                this._idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _recordNo
        {
            get
            {
                return this._recordNoField;
            }
            set
            {
                this._recordNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _content
        {
            get
            {
                return this._contentField;
            }
            set
            {
                this._contentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _againstFacts
        {
            get
            {
                return this._againstFactsField;
            }
            set
            {
                this._againstFactsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isPC
        {
            get
            {
                return this._isPCField;
            }
            set
            {
                this._isPCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _isFH
        {
            get
            {
                return this._isFHField;
            }
            set
            {
                this._isFHField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void UpLoadRecordCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void DownLoadRecordCompletedEventHandler(object sender, DownLoadRecordCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownLoadRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DownLoadRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public record[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((record[])(this.results[0]));
            }
        }
    }
}